repos:
-   repo: local
    hooks:
    - id: black
      name: black
      entry: python3 -m black . -l79
      language: system
      stages: [commit]
      types: [python]
-   repo: local
    hooks:
      - id: pydocstyle        
        args:
        - --ignore=D100,D104,D203,D213,D413
        name: pydocstyle
        entry: pydocstyle
        language: system
        stages: [commit]
-   repo: local
    hooks:
      - id: pycodestyle
        name: pycodestyle
        entry: pycodestyle
        language: system
        stages: [commit]
        types: [python]
